// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epgpfpazskxcsispbdra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwZ3BmcGF6c2t4Y3Npc3BiZHJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyMDc4ODcsImV4cCI6MjA0OTc4Mzg4N30.lBoTst5fAMEmhcHkmr-CYE6HCjYZEN4utahdsAQ7gbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);